services:
  phunkytech-web-svc:
    restart: always
    image: naijaautomator1/phunkytech-python:${TAG:-latest}
    ports:
      - "80:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      - phunkytechdata:/app/data
  phunkytech-redis-svc:
    image: redis
    volumes: 
      - phunkytechredisdata:/data
volumes:
  phunkytechdata:
  phunkytechredisdata:
