services:
  phunkytech-nginx-svc:
    image: nginx
  phunkytech-web-svc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      - phunkytechdata:/app/data
  phunkytech-redis-svc:
    image: redis
    volumes: 
      - phunkytechredisdata:/data
volumes:
  phunkytechdata:
  phunkytechredisdata:
