name: Build & Push Container
on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push the container images with Buildx
      - name: Build and push the container images
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag "$DH_USER/$REPO:latest" \
            --tag "$DH_USER/$REPO:${{ github.sha }}" \
            .


